// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCnsDjyuUkj5HE0dXnDMAxl3yr3SBs3AI',
    appId: '1:682436281252:android:9562eef8480e4dafbf7731',
    messagingSenderId: '682436281252',
    projectId: 'livilon-2b3f1',
    storageBucket: 'livilon-2b3f1.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyW0Eqms1JSdi3hazJJxE5AndjNyMb0dw',
    appId: '1:682436281252:ios:59a1e0f39eefc0ecbf7731',
    messagingSenderId: '682436281252',
    projectId: 'livilon-2b3f1',
    storageBucket: 'livilon-2b3f1.firebasestorage.app',
    androidClientId: '682436281252-j6mpgjt8p8hi2iebr5macq989frrmb4l.apps.googleusercontent.com',
    iosClientId: '682436281252-vtk2nrniv7lqnk59h7lrpgvb5p6ji8ur.apps.googleusercontent.com',
    iosBundleId: 'com.afreen.livilon',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyW0Eqms1JSdi3hazJJxE5AndjNyMb0dw',
    appId: '1:682436281252:ios:59a1e0f39eefc0ecbf7731',
    messagingSenderId: '682436281252',
    projectId: 'livilon-2b3f1',
    storageBucket: 'livilon-2b3f1.firebasestorage.app',
    androidClientId: '682436281252-j6mpgjt8p8hi2iebr5macq989frrmb4l.apps.googleusercontent.com',
    iosClientId: '682436281252-vtk2nrniv7lqnk59h7lrpgvb5p6ji8ur.apps.googleusercontent.com',
    iosBundleId: 'com.afreen.livilon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEndJ5XRq4bFITnOaWG1-Qkm2P3jFBrP8',
    appId: '1:682436281252:web:aab28966584b8cd2bf7731',
    messagingSenderId: '682436281252',
    projectId: 'livilon-2b3f1',
    authDomain: 'livilon-2b3f1.firebaseapp.com',
    storageBucket: 'livilon-2b3f1.firebasestorage.app',
    measurementId: 'G-G2H0J3G8V0',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEndJ5XRq4bFITnOaWG1-Qkm2P3jFBrP8',
    appId: '1:682436281252:web:a3b3c952055de890bf7731',
    messagingSenderId: '682436281252',
    projectId: 'livilon-2b3f1',
    authDomain: 'livilon-2b3f1.firebaseapp.com',
    storageBucket: 'livilon-2b3f1.firebasestorage.app',
    measurementId: 'G-BQC9KV1QHE',
  );

}